### ISSUE TITLE
docker安装不成功

### ISSUE THREAD

**Issue by 0ps** [momosecurity/Mloger#13]
提示：
Attaching to mloger-mongo-1, mloger-redis-1, mloger-web-1
mloger-redis-1  | find: .: Permission denied
mloger-redis-1  | chown: .: Permission denied
mloger-mongo-1  | find: '/data/db': Permission denied
mloger-mongo-1  | chown: changing ownership of '/data/db': Permission denied
mloger-redis-1 exited with code 1
mloger-mongo-1 exited with code 1
mloger-redis-1 exited with code 1
mloger-mongo-1 exited with code 1
mloger-redis-1 exited with code 1
mloger-mongo-1 exited with code 1
mloger-redis-1 exited with code 1
mloger-mongo-1 exited with code 1
mloger-mongo-1  | find: '/data/db': Permission denied
mloger-mongo-1  | chown: changing ownership of '/data/db': Permission denied
mloger-redis-1 exited with code 1
mloger-mongo-1 exited with code 1

**Comment by ResidualLaugh** [comment]
能否提供一下使用环境信息及复现步骤？

**Comment by 0ps** [comment]
cnetos7，直接按照你的readme来操作的

**Comment by 0ps** [comment]
![222](https://user-images.githubusercontent.com/3354553/156872732-2d95e180-1dc2-40bf-b363-ba2388af3b43.PNG)

**Comment by ResidualLaugh** [comment]
docker安装成功了吗？这个弹窗是如何触发的？
