### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by 0ps** [momosecurity/Mloger#17]
centos7，使用docker安装。
![微信截图_20220827235127](https://user-images.githubusercontent.com/3354553/187037824-9c05f07c-7795-47b6-8608-4b3f05e10031.png)
上方一直弹报错的红点
http能抓到抱，但是没有返回，ws直接抓不到

**Comment by ResidualLaugh** [comment]
ws的内容要在TCP/WS测试中看。
没有返回包看一下代理有报错没？

**Comment by ResidualLaugh** [comment]
大佬加我微信吧，详细说说 canxiao_xiao
