### ISSUE TITLE
代理端口无法启动

### ISSUE THREAD

**Issue by 0ps** [momosecurity/Mloger#2]
[root@localhost server]# python3 app.py
2525|2022-01-05 04:35:00,268|INFO|log|server.py|server|168|Server initialized for gevent.
2525|2022-01-05 04:35:00,278|WARNING|log|app.py|app|16|start proxy
2525|2022-01-05 04:35:00,283|WARNING|log|proxy_server.py|proxy_server|40|start http proxy on 8081 port, pid 2534
2525|2022-01-05 04:35:00,287|WARNING|log|proxy_server.py|proxy_server|53|start socks proxy on 8082 port, pid 2537
2525|2022-01-05 04:35:00,287|WARNING|log|app.py|app|16|start task
2525|2022-01-05 04:35:00,287|WARNING|log|match.py|match|13|start add2apis
2525|2022-01-05 04:35:00,288|WARNING|log|match.py|match|53|start timeout_for_ip_acl
Error: mitmproxy's console interface requires a tty. Please run mitmproxy in an interactive shell environment.
Error: mitmproxy's console interface requires a tty. Please run mitmproxy in an interactive shell environment.

**Comment by ResidualLaugh** [comment]
看报错是mitmproxy在子进程中执行导致的，它是无法在子进程中执行的，项目里没有使用mitmproxy而是用mitmdump替代了它。请问是否修改了server/proxy/proxy_server.py 中mitmdump_path呢？项目里使用的mitmdump是可以正常执行的。

**Comment by ResidualLaugh** [comment]
@0ps 请问这个问题被解决了吗？我看到这个issue一周没有回复了，如果依旧出现这个问题希望能够提供更详细的使用描述，否则我将在下周关闭这个issue。
