### ISSUE TITLE
切换菜单状态数据丢失

### ISSUE THREAD

**Issue by testivy** [momosecurity/Mloger#4]
**切换功能菜单会导致原来的状态丢失**

例如 HTTP记录这里是连接状态
![image](https://user-images.githubusercontent.com/79240946/149662765-171ca8f8-7f2b-4e77-8256-e6b036dd3e76.png)

当切到其他菜单后再切换回来原来的记录会消失
![image](https://user-images.githubusercontent.com/79240946/149662673-d9a45f76-7dae-48f8-abb4-63cc099d0fd7.png)

**Comment by ResidualLaugh** [comment]
在HTTP记录页点击切换其他功能菜单时会新建标签页，而不是在当前标签页中打开。原有的HTTP记录页数据和状态会继续保留，点击原有标签页可切换回正在使用的HTTP记录页面。如下图所示
![image](https://user-images.githubusercontent.com/23581090/149691979-1076cf61-8928-48b4-ae24-5b626034bf5f.png)

**Comment by testivy** [comment]
已解决，谢谢
